### ISSUE TITLE
API error: undefined

### ISSUE THREAD

**Issue by fromb2b** [feross/reddit#2]
Hi
  I tried to fetch some data using two methods: async await and reddit.get().then().catch().

For example:
reddit.get('/api/trending_subreddits',{}).then((res)=> {console.log(res)}).catch((err)=>{console.log(err)});

Both caused this error:
  Error: API error: undefined. Status code: 404
    at get.concat (C:\Users\hp\Desktop\API_TEST\node_modules\reddit\index.js:152:13)
    at concat (C:\Users\hp\Desktop\API_TEST\node_modules\simple-get\index.js:89:7)
    at IncomingMessage.<anonymous> (C:\Users\hp\Desktop\API_TEST\node_modules\simple-concat\index.js:7:13)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

I have another question regarding credentials: Does appId correspond to the string generated next to ? symbol in reddit api preferences and can I use your module for both web apps and scripts .

Thank you.

**Comment by feross** [comment]
There seems to be something wrong with the `/api/trending_subreddits` endpoint. I can't get it to return anything except 400. I did merge this bugfix: https://github.com/feross/reddit/pull/1 though which fixes `reddit.get`.

This code works just fine, for example:

```js
reddit.get('/best',{}).then((res)=> {console.log(res)}).catch((err)=>{console.log(err)});
```

This package probably won't work in the browser because I doubt that the reddit API sets the appropriate CORS headers, but maybe give it a shot and see if it works?
